# Project: Project3
# Makefile created by Dev-C++ 5.4.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Globals.o Draw.o Game.o Menu.o main.o
LINKOBJ  = Globals.o Draw.o Game.o Menu.o main.o
LIBS     = -L"D:/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 
INCS     = -I"D:/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW32/include"
BIN      = Song_Sot_Giua_Vong_Vay.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Globals.o: Globals.cpp
	$(CPP) -c Globals.cpp -o Globals.o $(CXXFLAGS)

Draw.o: Draw.cpp
	$(CPP) -c Draw.cpp -o Draw.o $(CXXFLAGS)

Game.o: Game.cpp
	$(CPP) -c Game.cpp -o Game.o $(CXXFLAGS)

Menu.o: Menu.cpp
	$(CPP) -c Menu.cpp -o Menu.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
